[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/discord.js/**/*"]

# API redirects for Discord functions
[[redirects]]
  from = "/api/discord-create-channel"
  to = "/.netlify/functions/discord-create-channel"
  status = 200
  force = true

[[redirects]]
  from = "/api/discord/*"
  to = "/.netlify/functions/discord-:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/discord-add-member"
  to = "/.netlify/functions/discord-add-member"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18.17.0" 